Disable idle pool to maybe fix an edge case error
```
Error: Request Error when talking to qbittorrent: error sending request for url (http://localhost:6006/api/v2/torrents/delete): connection closed before message completed

Caused by:
    0: error sending request for url (http://localhost:6006/api/v2/torrents/delete): connection closed before message completed
    1: connection closed before message completed
```
Issue: https://github.com/hyperium/hyper/issues/2136